import '@vite/client'
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./index.css";
import { BrowserRouter } from "react-router-dom";
import { AuthProvider } from "./context/AuthContext.jsx";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <BrowserRouter>
      <AuthProvider>
        <App />
      </AuthProvider>
    </BrowserRouter>
  </React.StrictMode>
);

// Service worker registration fallback (useful for preview/dev and to ensure
// the PWA plugin is registering correctly). This will silently fail in
// environments where a service worker is not available.
if ('serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('/sw.js').catch((err) => {
      // sw.js may be generated by the Vite PWA plugin in production/build.
      // In dev mode it's okay if this registration fails — log for debugging.
      // eslint-disable-next-line no-console
      console.info('Service worker registration (fallback) failed:', err.message);
    });
  });
}
